# -*- coding: utf-8 -*-
"""Verifica_TAU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxwNRveowb53VhkwwYp5w0wUngd-5NXC
"""

# =====================================================================
#  TEST OOD da URL - script standalone per Google Colab
#  Invece di una cartella, passi il LINK di una (o piu') immagini e vedi
#  cosa predice il modello. Per ogni immagine stampa:
#    - psi_a  = confidenza massima (prob. dell'argmax)   <-- il numero chiave
#    - argmax = classe predetta senza reject
#    - routed = classe finale con la reject option (-> undifferentiated se incerto)
# =====================================================================

# ---------------------------------------------------------------------
# CELLA 1 - Monta Google Drive
# ---------------------------------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

# ---------------------------------------------------------------------
# CELLA 2 - CONFIGURAZIONE
# ---------------------------------------------------------------------
EXP_DIR = ("/content/drive/MyDrive/Progetto Machine Learning/"
           "Image-Based-Waste-Classification/experiments/"
           "efficientnet_b3_20260630_035949")

MODEL_PATH = EXP_DIR + "/models/final_ft.pth"   # se non esiste, vedi CELLA 2b
MODEL_NAME = "efficientnet_b3"                   # deve corrispondere ai pesi

# >>> METTI QUI I LINK DELLE IMMAGINI DA TESTARE (uno o piu') <<<
IMAGE_URLS = [
    "https://img.magnific.com/foto-gratuito/adorabile-cane-basenji-marrone-e-bianco-che-sorride-e-che-da-il-cinque-isolato-su-bianco_346278-1657.jpg?semt=ais_hybrid&w=740&q=80",
    "https://images.ctfassets.net/hrltx12pl8hq/7vd4eckqr4joKNKwWUv0Mg/844d9d491f4ab942a90259d44bbcfa01/dogs-images.jpg?fit=fill&w=1200&h=630",
    "https://www.osservatoriodellaplastica.com/wp-content/uploads/2022/11/AdobeStock_323435465-scaled.jpeg",
    "https://www.federdistribuzione.it/app/uploads/2021/06/coripet.png",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA8BGERwCpTWCSrhSYVb7Jjg-Rb6ZqaN4jcdrK1CqnlA&s=10",
]

# Temperatura e soglia dalla tua calibrazione (dal log / final_test_metrics.json):
T   = 1.0
TAU = 0.10

DROPOUT = 0.3
N_CLASSES = 8

CLASS_NAMES = ['battery', 'clothing', 'glass', 'metal',
               'organic', 'papery', 'plastic', 'undifferentiated']
UNDIFF_IDX = 7
CARVEOUT_INDICES = [CLASS_NAMES.index('plastic'),
                    CLASS_NAMES.index('glass'),
                    CLASS_NAMES.index('metal')]

_INPUT_SIZES = {'efficientnet_b0': 224, 'efficientnet_b2': 288,
                'efficientnet_b3': 300, 'mobilenet_v3_small': 224}
INPUT_SIZE = _INPUT_SIZES[MODEL_NAME]

# ---------------------------------------------------------------------
# CELLA 2b - CONTROLLO: cosa c'e' nella cartella models/
# ---------------------------------------------------------------------
import os
models_dir = EXP_DIR + "/models"
print("Contenuto di", models_dir, ":")
if os.path.isdir(models_dir):
    for f in sorted(os.listdir(models_dir)):
        print("  ", f)
    if not os.path.exists(MODEL_PATH):
        print("\n[ATTENZIONE] final_ft.pth NON trovato: usa un fold*_ft.pth elencato sopra.")
else:
    print("  [ERRORE] La cartella non esiste: controlla EXP_DIR.")

# ---------------------------------------------------------------------
# CELLA 3 - Ricostruisci il modello e carica i pesi
# ---------------------------------------------------------------------
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms
from PIL import Image
import requests
from io import BytesIO

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def build_model(model_name, num_classes, dropout):
    if model_name == "efficientnet_b0":
        model = models.efficientnet_b0(weights=None)
    elif model_name == "efficientnet_b2":
        model = models.efficientnet_b2(weights=None)
    elif model_name == "efficientnet_b3":
        model = models.efficientnet_b3(weights=None)
    elif model_name == "mobilenet_v3_small":
        model = models.mobilenet_v3_small(weights=None)
        in_feats = model.classifier[3].in_features
        model.classifier[2] = nn.Dropout(p=dropout, inplace=True)
        model.classifier[3] = nn.Linear(in_feats, num_classes)
        return model
    else:
        raise ValueError(model_name)
    num_ftrs = model.classifier[1].in_features
    model.classifier[0] = nn.Dropout(p=dropout, inplace=True)
    model.classifier[1] = nn.Linear(num_ftrs, num_classes)
    return model

model = build_model(MODEL_NAME, N_CLASSES, DROPOUT)
state = torch.load(MODEL_PATH, map_location=device)
if isinstance(state, dict) and 'state_dict' in state:
    state = state['state_dict']
missing, unexpected = model.load_state_dict(state, strict=False)
if missing or unexpected:
    print(f"[Attenzione] missing={missing}  unexpected={unexpected} (MODEL_NAME non combacia?)")
model = model.to(device).eval()
print(f"Modello {MODEL_NAME} caricato su {device}. Input size = {INPUT_SIZE}px")

# ---------------------------------------------------------------------
# CELLA 4 - Preprocessing IDENTICO al training + funzioni
# ---------------------------------------------------------------------
preprocess = transforms.Compose([
    transforms.Resize(INPUT_SIZE + 32),
    transforms.CenterCrop(INPUT_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

def load_image_from_url(url):
    headers = {"User-Agent": "Mozilla/5.0"}  # alcuni siti bloccano richieste senza UA
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    return Image.open(BytesIO(r.content)).convert('RGB')

def route_label(probs_row, tau):
    max_p, pred = float(probs_row.max()), int(probs_row.argmax())
    top2 = probs_row.topk(2).indices.tolist()
    in_carveout = all(c in CARVEOUT_INDICES for c in top2)
    if (max_p < tau) and (not in_carveout):
        return UNDIFF_IDX, max_p
    return pred, max_p

# ---------------------------------------------------------------------
# CELLA 5 - Predici dai link e stampa il risultato
# ---------------------------------------------------------------------
from IPython.display import display

print(f"{'psi_a':>7}  {'ARGMAX':<15} {'ROUTED (reject)':<18}  URL")
print("-" * 90)
for url in IMAGE_URLS:
    try:
        img = load_image_from_url(url)
    except Exception as e:
        print(f"[ERRORE scaricamento] {url}\n   {e}")
        continue

    x = preprocess(img).unsqueeze(0).to(device)
    with torch.no_grad():
        probs = F.softmax(model(x) / T, dim=1)[0].cpu()
    routed, psi = route_label(probs, TAU)
    argmax = int(probs.argmax())

    # mostra l'immagine (anteprima piccola) + verdetto
    display(img.resize((160, 160)))
    print(f"{psi:>7.3f}  {CLASS_NAMES[argmax]:<15} {CLASS_NAMES[routed]:<18}  {url[:50]}")

    # top-3 probabilita', utile per capire dove il modello 'butta' l'OOD
    top3 = torch.topk(probs, 3)
    tops = ", ".join(f"{CLASS_NAMES[i]}={p:.2f}"
                     for p, i in zip(top3.values.tolist(), top3.indices.tolist()))
    print(f"         top-3: {tops}\n")

print("Interpretazione: psi_a basso -> il modello 'sa di non sapere' (reject sensata).")
print("psi_a alto su un OOD (es. cane=plastica 0.95) -> modello overconfident,")
print("il softmax da solo non e' un buon detector open-set (risultato da report).")